name: AutoReviewBot
on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write
  issues: write  # Add this

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install @actions/core
          npm install @actions/github
          npm install js-yaml
          npm install parse-diff
          
      - name: Run AutoReviewBot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this is correct
        run: |
          echo "GITHUB_TOKEN length: ${#GITHUB_TOKEN}"  # Debug token presence
          node bot.js
