name: AutoReviewBot
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]  # Add this
    branches: [main]  # Add this

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    # Remove container section for quick testing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Run Bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node bot.js
