name: Run AutoReviewBot

on: 
  pull_request: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node bot.js
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
