name: Run AutoReviewBot

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
        
      - name: Run AutoReviewBot
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node bot.js
